// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oepewrfoqueaksvfscdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lcGV3cmZvcXVlYWtzdmZzY2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MzA4MDksImV4cCI6MjA2NTMwNjgwOX0.ZBDbOy5Ea1390rZG_uAX3Dii7RiMocrGczTOt7Rrmbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);